
#DoesPotatoTick?
["Living Entities Tick Settings"]
	#If you disable this, entities will not stop ticking when they're far from you, this mod may be useless for you too
	OptimizeEntitiesTicking = true
	#If you don't want an entity to be affected by the optimization, you can write its registry name down here.
	EntitiesWhitelist = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:wither", "minecraft:player", "mowziesmobs:barako", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "mowziesmobs:naga", "blue_skies:alchemist", "blue_skies:arachnarch", "blue_skies:starlit_crusher", "blue_skies:summoner", "stalwart_dungeons:awful_ghast", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:shelterer_without_armor", "dungeonsmod:extrapart", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:ignis", "cataclysm:ignited_revenant", "cataclysm:netherite_monstrosity", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:dragon_multipart", "minecraft:lightning_bolt", "bclib:chair", "scguns:projectile", "scguns.bearpack_shell_projectile", "scguns.osborne_slug_projectile", "scguns.plasma_projectile", "scguns.ramrod_projectile", "scguns.hog_round_projectile", "scguns.beowulf_projectile", "scguns.fire_round_projectile", "scguns.grenade", "scguns.rocket", "scguns.microjet", "scguns.shulkshot_projectile", "scguns.sculk_cell", "scguns.krahg_round_projectile", "scguns.advanced_round_projectile", "scguns.throwable_grenade", "scguns.throwable_stun_grenade", "scguns.throwable_molotov_cocktail", "scguns.throwable_choke_bomb", "scguns.throwable_swarm_bomb", "scguns.throwable_gas_grenade", "scguns.blaze_rod_projectile", "scguns.basic_bullet_projectile", "scguns.hardened_bullet_projectile", "scguns.buckshot_projectile", "scguns.syringe_projectile", "scguns.gibbs_round_projectile", "ars_nouveau.spell_proj", "ars_nouveau.arcing_spell_proj", "ars_nouveau.homing_spell_proj"]
	#If you don't want entities of a mod to be affected by the optimization, you can write its modid down here
	EntitiesModIDWhiteList = ["create", "witherstormmod", "minecolonies", "automobility", "furnish", "handcrafted", "decoration_delight", "true_ending", "littlecontraptions", "littlelogistics"]
	#Similar to entity whitelist, but only take effect in raid.
	RaidEntitiesWhiteList = ["minecraft:witch", "minecraft:vex"]
	#Similar to entity modID whitelist, but only take effect in raid
	RaidEntitiesModIDWhiteList = []
	#Leave this empty for applying to all the dimensions
	#Entities in these dimensions will be affected by the optimization
	DimensionWhitelist = []
	#With this turned on, all the raider will always tick if the world has raids
	TickRaidersIfRaid = true
	#If this is enabled, hostile entities will always tick
	IgnoreHostileEntities = false
	#If this is enabled, projectiles will always tick
	IgnoreProjectiles = true
	#If this is enabled, optimization will only take effect on living entities
	OnlyLivingOptimizable = false
	#Range: > 1
	LivingEntitiesMaxHorizontalTickDistanceInChunks = 4
	#Range: > 1
	LivingEntitiesMaxVerticalTickDistanceInChunks = 2

["Item Entities Tick Settings"]
	#Slow down item entities' ticking speed
	#Note this does impact rendering continuity, so this optimization is disabled by default
	OptimizeItemMovement = true
	#If you don't want to let a specific item entity in the world to be effected by the optimization, you can write its registry name down here.
	#Require 'OptimizeItemMovement' to be true
	ItemWhiteList = ["minecraft:cobblestone"]
	#If this is enabled, item entities will always tick
	IgnoreItemEntities = false

[Misc]
	SendWarningMessageWhenPlayerLogIn = false
	#If enabled, entities ticking in other threads will not be affected
	OnlyWorksOnServerThread = true

[Client]
	#If the tick of an entity is skipped by this mod, stop its client rendering so that players won't get it stuck in their worlds.
	StopRenderingSkippedEntities = true

